#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_start-http-server" "$ROOT/assets"

cd "$ROOT"

for E in $(cargo run --example 2>&1 | grep --extended-regexp '^    ' | sort); do
    m "\nexample: $E\n" "$RED"
    RUSTFLAGS='-Z threads=8 --codegen linker=clang --codegen link-arg=--ld-path=wild' \
	cargo +nightly run --quiet --example "$E" --features=blocking,async
done
